### ISSUE TITLE
Ideas for MiniProject1

### ISSUE THREAD

**Issue by AndersonWalsh** [troy51538/MiniProject1#1]
Hey @troy51538. I have a couple ideas for project #1 that I'm going between for term frequency analysis. First, I was thinking about looking at emails for spam filtering. But I also thought it might be interesting to examine old textbooks vs new textbooks of a particular discipline to see how that areas has progressed (CS, medicine, etc). Interested to hear what you think. Thanks!

**Comment by troy51538** [comment]
I think both ideas are really interesting, but I am slightly leaning more towards the second idea. Maybe we could compare textbooks by each decade or by every 5 years, etc?
